include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - sort_pub_dependencies

analyzer:
  exclude:
    - example/**
    - "**/*.g.dart"
  errors:
    missing_required_param: error
    missing_return: error
